### PR TITLE
[RTL13] Fix existing impl. for server sent DETACH

### LINKED ISSUE #1051: [RTL13] Handle server sent `DETACHED` event
- Currently, [RTL13](https://sdk.ably.com/builds/ably/specification/main/features/#RTL13) is partially implemented.
- This is needed for https://github.com/ably/ably-chat-kotlin/issues/25

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5172) by [Unito](https://www.unito.io)

### LINKED ISSUE #1055: Flaky realtime tests for RealtimeChannelTest
- Consistent failing integration tests for `RealtimeChannelTest` are being observed.
- Tests seem to be working on local, so flakiness is mostly observed on the CI.
- Cause mostly seems to be recent merged PR https://github.com/ably/ably-java/pull/1052.
- Aim to remove CI flakiness for all `RealtimeChannelTest.java` tests.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5180) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by sacOO7**
- Fixed #1051 
- Fixed #1055 
- Fixed missing RTL5g impl. from https://github.com/ably/ably-java/issues/1045

## Summary by CodeRabbit

- **New Features**
	- Enhanced handling of channel state transitions and error information during attachment and detachment processes.
	- Added a new test to verify channel behavior during detach events in suspended state.

- **Bug Fixes**
	- Streamlined reattachment logic for channels after unexpected detach events.
	- Improved error handling to ensure accurate propagation during channel state changes.

- **Refactor**
	- Clarified state management logic and updated method signatures for better clarity and efficiency.

### CODE REVIEW

**Review by ttypic — APPROVED** [review]
Looks good to me, but we’re still not fully spec-compliant. The error reason from the detach message should be propagated in the state change

File: lib/src/main/java/io/ably/lib/realtime/ChannelBase.java [hunk 1]
```diff
@@ -90,6 +90,16 @@ public abstract class ChannelBase extends EventEmitter<ChannelEvent, ChannelStat
      */
     private boolean released = false;
 
+    private ErrorInfo msgError;
+
+    private ErrorInfo getMsgError() {
```
[the remark this answers is not in the document]
Comment (sacOO7) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java:95]: Yeah, we can rename it since it's not a perfect getter

File: lib/src/main/java/io/ably/lib/realtime/ChannelBase.java [hunk 2]
```diff
@@ -90,6 +90,16 @@ public abstract class ChannelBase extends EventEmitter<ChannelEvent, ChannelStat
      */
     private boolean released = false;
 
+    private ErrorInfo msgError;
```
[the remark this answers is not in the document]
Comment (sacOO7) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java:93]: I will try refactoring existing `attachWithTimer` signature but it can affect it's usages across codebase.
If not possible, I will revert the change

[the remark this answers is not in the document]
Comment (sacOO7) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java]: Okay updated https://github.com/ably/ably-java/pull/1054/commits/0dfc6c3cc203694f8d0e467105e0bea5775a047b

File: lib/src/main/java/io/ably/lib/realtime/ChannelBase.java [hunk 3]
```diff
@@ -217,7 +217,7 @@ synchronized void transferQueuedPresenceMessages(List<QueuedMessage> messagesToT
 
     private boolean attachResume;
 
-    private void attachImpl(final boolean forceReattach, final CompletionListener listener) throws AblyException {
+    private void attachImpl(final boolean forceReattach, final CompletionListener listener, ErrorInfo msgErr) throws AblyException {
```
Comment (ttypic) [inline lib/src/main/java/io/ably/lib/realtime/ChannelBase.java:220]: I suggest using `reattachmentReason` instead of `msgErr`

Comment (sacOO7) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java:220]: or `attachmentReason` because `attachImpl` is triggered by both `explicit` and `implicit` attach

Comment (sacOO7) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java:220]: or simply `reason`, since `attachImpl` method already implies it's channel attach operation wdyt?

Comment (ttypic) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java:220]: `reattachmentReason` a bit more specific, cause this is not null only in the case of reattachment, but I have no objections to the `reason`

Comment (sacOO7) [reply lib/src/main/java/io/ably/lib/realtime/ChannelBase.java]: Okay, updated to `reattachmentReason`.
Not sure why `should_have_serial_action_createdAt` is failing, it's also failing on `main`. 
Probably sandbox issue ?

**Review by ttypic — APPROVED** [review]
