### PR TITLE
Use exception instead of deprecation notice

### LINKED ISSUE #139: For 0.9, replace deprecation notice by an exception in BaseMessage.encode.
Basically, [this line](https://github.com/ably/ably-java/blob/16a865928919cae5482793f37a5cf44069e0c95e/lib/src/main/java/io/ably/lib/types/BaseMessage.java#L122) should be removed and [this one](https://github.com/ably/ably-java/blob/16a865928919cae5482793f37a5cf44069e0c95e/lib/src/main/java/io/ably/lib/types/BaseMessage.java#L120) should run unconditionally, ie. removing [this condition](https://github.com/ably/ably-java/blob/16a865928919cae5482793f37a5cf44069e0c95e/lib/src/main/java/io/ably/lib/types/BaseMessage.java#L119).

See #137.

### PR DESCRIPTION
**Pull request by funkyboy**
Fix #139

### CODE REVIEW

File: lib/src/main/java/io/ably/lib/types/BaseMessage.java [hunk 1]
```diff
@@ -131,11 +131,7 @@ public void encode(ChannelOptions opts) throws AblyException {
 					encoding = ((encoding == null) ? "" : encoding + "/") + "utf-8";
 				}
 			} else if(!(data instanceof byte[])) {
-				if (opts != null && opts.encrypted) {
 					throw AblyException.fromErrorInfo(new ErrorInfo("Invalid message data or encoding", 400, 40013));
```
Comment (paddybyers) [inline lib/src/main/java/io/ably/lib/types/BaseMessage.java]: Surely we also need a whitespace change here as well?

Comment (funkyboy) [reply lib/src/main/java/io/ably/lib/types/BaseMessage.java]: Yup. Fixed.

**Comment by funkyboy** [comment]
@paddybyers Yup. Fixed.
