### PR TITLE
Ensure graceful handling of DETACH and DISCONNECT.

### LINKED ISSUE #130: Important: Ensure DETACHED or DISCONNECTED with error is non-fatal
See a bug discovered today at https://github.com/ably/ably-js/issues/312 for ably-js.

This is quite problematic because if we explicitly have to DETACH a channel (due to a timeout for example), then the client now will move the channel into the failed state.  This means most customers will never re-attach that channel automatically, see https://www.ably.io/documentation/realtime/connection#handling-failures.

With some urgency, we need to add test coverage to ensure that:

* A server initiated `DETACH` with or without an error moves the channel to the `DETACHED` state and not a failed state
* A server initiated `DISCONNECT` with or without an error moves the connection to the `DISCONNECTED` state and not a failed state.

### PR DESCRIPTION
**Pull request by tcard**
Fixes #130.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Nice :) Thanks @tcard

File: lib/src/main/java/io/ably/lib/transport/ConnectionManager.java [hunk 1]
```diff
@@ -269,7 +269,7 @@ public void run() {
 	 * transport events/notifications
 	 ***************************************/
 
-	void onMessage(ProtocolMessage message) throws AblyException {
+	public void onMessage(ProtocolMessage message) throws AblyException {
```
Comment (paddybyers) [inline lib/src/main/java/io/ably/lib/transport/ConnectionManager.java]: It's a shame we need to make this public just in order to be able to call it from a test. I can't think of an alternative at the moment without mocking the transport so the message comes from there.

**Comment by paddybyers** [comment]
LGTM, thanks

File: lib/src/main/java/io/ably/lib/transport/ConnectionManager.java (hunk 1 above)
Comment (mattheworiordan) [inline lib/src/main/java/io/ably/lib/transport/ConnectionManager.java]: > It's a shame we need to make this public just in order to be able to call it from a test. I can't think of an alternative at the moment without mocking the transport so the message comes from there.

I don't know if there is a convention if Java, but in Ruby you can add `@api private` to the method so that at least it's documented clearly that the method is public, but not as part of the public API
